// Autogenerated file by build.py, don't change!

package org.renpy.android;
import android.content.Intent;

public class Configuration {
	/* Billing configuration */
	{% if args.billing_pubkey %}
	static public boolean use_billing = true;
	static public String billing_pubkey = "{{ args.billing_pubkey }}";
	{% else %}
	static public boolean use_billing = false;
	static public String billing_pubkey = null;
	{% endif %}
	static public byte billing_salt[] = new byte[] {41, -90, -116, -41, 66, -53, 122, -110, -127, -96, -88, 77, 127, 115, 1, 73, 57, 110, 48, -116};

	/* Loader configuration */
	{% if args.launch_intent %}
	static public boolean use_intent = true;
	{% else %}
	static public boolean use_intent = false;
	{% endif %}
	{% if args.launch_intent and args.launch_intent.endswith(".class") %}
	static public Intent launch_intent = Intent(this, {{ args.launch_intent }});
	{% elif args.launch_intent %}
	static public Intent launch_intent = Intent(this, "{{ args.launch_intent }}");
	{% else %}
	static public Intent launch_intent = null;
	{% endif %}
}
